name: Daily Token Holders Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar a las 00:00 UTC cada día
  workflow_dispatch:      # Permite ejecutar manualmente desde GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4    # También actualizamos checkout a v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # Actualizamos setup-python a v5
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase selenium

    - name: Run scraper
      run: python scrap.py  # Cambia aquí a 'scrap.py'
      
    - name: Upload results
      uses: actions/upload-artifact@v4  # Actualizado a v4
      with:
        name: token-holders-data
        path: Smol_Holders/
        retention-days: 5  # Opcional: especifica cuántos días mantener los artifacts

    - name: Upload screenshot
      if: failure()  # Solo subir la captura si falla el script
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: Smol_Holders/error_*.png  # Esto incluye cualquier archivo de captura de pantalla que empiece con "error_"
        retention-days: 5  # Opcional: especifica cuántos días mantener los artifacts
